spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_development
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: mybatis/**/*.xml
