spring:
  datasource:
    url: jdbc:h2:/tmp/h2/test
    username: root
    password: root
  h2:
    console:
      enabled: true

mybatis:
  type-handlers-package: com.onigra.test.infrastructure.datasource